### ISSUE TITLE
Tapjoy connect call failes in release mode

### ISSUE THREAD

**Issue by dr4xor** [AnavrinApps/flutter_tapjoy#1]
Hi there,
I am currently facing a strange issue with the Tapjoy integration.
When building in debug mode, the Tapjoy connect call is successful and everything works as expected.

However when I run the app in release mode the Tapjoy connect call failes everytime.

It can be reproduced by building the example project in release mode.

**Comment by AnavrinApps** [comment]
Hey Marco,
Are you facing this error with the Android or the iOS version of Tapjoy?
Regards,
Anavrin Apps

**Comment by AnavrinApps** [comment]
Could you try declaring this in your proguard file and try -

-keep class com.tapjoy.** { *; }-keep class com.moat.** { *;
}-keepattributes JavascriptInterface-keepattributes *Annotation*-keep
class * extends java.util.ListResourceBundle {protected Object[][]
getContents();}-keep public class
com.google.android.gms.common.internal.safeparcel.SafeParcelable
{public static final *** NULL;}-keepnames
@com.google.android.gms.common.annotation.KeepName class
*-keepclassmembernames class *
{@com.google.android.gms.common.annotation.KeepName *;}-keepnames
class * implements android.os.Parcelable {public static final **
CREATOR;}-keep class com.google.android.gms.ads.identifier.** { *;
}-dontwarn com.tapjoy.**

**Comment by dr4xor** [comment]
It worked, thank you very much!
