### ISSUE TITLE
Does not work in production

### ISSUE THREAD

**Issue by sampathkumar7** [AnavrinApps/flutter_tapjoy#3]
It works in testing but not working in production mode please help how to fix.

**Comment by AnavrinApps** [comment]
Please add these lines to your proguard - 
-keep class com.tapjoy.** { *; }
    -keep class com.moat.** { *; }
    -keepattributes JavascriptInterface
    -keepattributes *Annotation*
    -keep class * extends java.util.ListResourceBundle {
     protected Object[][] getContents();
    }
    -keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
    public static final *** NULL;
    }
    -keepnames @com.google.android.gms.common.annotation.KeepName class *
    -keepclassmembernames class * {
    @com.google.android.gms.common.annotation.KeepName *;
    }
    -keepnames class * implements android.os.Parcelable {
    public static final ** CREATOR;
    }
    -keep class com.google.android.gms.ads.identifier.** { *; }
    -dontwarn com.tapjoy.**
